version: '3'

services:
  db:
    image: mysql/mysql-server
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wanghui
      MYSQL_PASSWORD: wanghui
    volumes:
      - /docker/mysql/mysql-init:/docker-entrypoint-initdb.db
  web:
    build:
      context: .
      dockerfile: Web/Dockerfile
    container_name: aspnetcore
    ports:
      - '80:80'
    depends_on:
      - db